{
  imports = [
    ./bat.nix
    #./chromium.nix
    ./google-chrome.nix
    ./eza.nix
    ./git.nix
    ./ghostty.nix
    ./hyprland
    ./lazygit.nix
    ./neovim.nix
    ./obsidian.nix
    #./ranger.nix
    ./starship.nix
    ./stylix.nix
    ./swaync
    ./tmux.nix
    ./waybar
    ./wofi
    ./vscode.nix
    ./yazi.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
